
package mk.nbrm.klservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This web service provides information about NBRM's exchange rates.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Kurs", targetNamespace = "http://www.nbrm.mk/klservice/", wsdlLocation = "http://www.nbrm.mk/klservice/kurs.asmx?wsdl")
public class Kurs
    extends Service
{

    private final static URL KURS_WSDL_LOCATION;
    private final static WebServiceException KURS_EXCEPTION;
    private final static QName KURS_QNAME = new QName("http://www.nbrm.mk/klservice/", "Kurs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.nbrm.mk/klservice/kurs.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KURS_WSDL_LOCATION = url;
        KURS_EXCEPTION = e;
    }

    public Kurs() {
        super(__getWsdlLocation(), KURS_QNAME);
    }

    public Kurs(WebServiceFeature... features) {
        super(__getWsdlLocation(), KURS_QNAME, features);
    }

    public Kurs(URL wsdlLocation) {
        super(wsdlLocation, KURS_QNAME);
    }

    public Kurs(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KURS_QNAME, features);
    }

    public Kurs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Kurs(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KursSoap
     */
    @WebEndpoint(name = "KursSoap")
    public KursSoap getKursSoap() {
        return super.getPort(new QName("http://www.nbrm.mk/klservice/", "KursSoap"), KursSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KursSoap
     */
    @WebEndpoint(name = "KursSoap")
    public KursSoap getKursSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.nbrm.mk/klservice/", "KursSoap"), KursSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KURS_EXCEPTION!= null) {
            throw KURS_EXCEPTION;
        }
        return KURS_WSDL_LOCATION;
    }

}
