package nbrm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.oracle.xmlns.internal.webservices.jaxws_databinding.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KursSoap", targetNamespace = "http://www.nbrm.mk/klservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KursSoap {


    /**
     * This XML Web Service method provides information about exchang rate
     * 
     * @param endDate
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExchangeRateD", action = "http://www.nbrm.mk/klservice/GetExchangeRateD")
    @WebResult(name = "GetExchangeRateDResult", targetNamespace = "http://www.nbrm.mk/klservice/")
    @RequestWrapper(localName = "GetExchangeRateD", targetNamespace = "http://www.nbrm.mk/klservice/", className = "mk.nbrm.klservice.GetExchangeRateD")
    @ResponseWrapper(localName = "GetExchangeRateDResponse", targetNamespace = "http://www.nbrm.mk/klservice/", className = "mk.nbrm.klservice.GetExchangeRateDResponse")
    public String getExchangeRateD(
        @WebParam(name = "StartDate", targetNamespace = "http://www.nbrm.mk/klservice/")
        XMLGregorianCalendar startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.nbrm.mk/klservice/")
        XMLGregorianCalendar endDate);

    /**
     * This XML Web Service method provides information about exchang rate
     * 
     * @param endDate
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExchangeRate", action = "http://www.nbrm.mk/klservice/GetExchangeRate")
    @WebResult(name = "GetExchangeRateResult", targetNamespace = "http://www.nbrm.mk/klservice/")
    @RequestWrapper(localName = "GetExchangeRate", targetNamespace = "http://www.nbrm.mk/klservice/", className = "mk.nbrm.klservice.GetExchangeRate")
    @ResponseWrapper(localName = "GetExchangeRateResponse", targetNamespace = "http://www.nbrm.mk/klservice/", className = "mk.nbrm.klservice.GetExchangeRateResponse")
    public String getExchangeRate(
        @WebParam(name = "StartDate", targetNamespace = "http://www.nbrm.mk/klservice/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.nbrm.mk/klservice/")
        String endDate);

    /**
     * This XML Web Service method provides information about exchange rates
     * 
     * @param endDate
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExchangeRatesD", action = "http://www.nbrm.mk/klservice/GetExchangeRatesD")
    @WebResult(name = "GetExchangeRatesDResult", targetNamespace = "http://www.nbrm.mk/klservice/")
    @RequestWrapper(localName = "GetExchangeRatesD", targetNamespace = "http://www.nbrm.mk/klservice/", className = "mk.nbrm.klservice.GetExchangeRatesD")
    @ResponseWrapper(localName = "GetExchangeRatesDResponse", targetNamespace = "http://www.nbrm.mk/klservice/", className = "mk.nbrm.klservice.GetExchangeRatesDResponse")
    public String getExchangeRatesD(
        @WebParam(name = "StartDate", targetNamespace = "http://www.nbrm.mk/klservice/")
        XMLGregorianCalendar startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.nbrm.mk/klservice/")
        XMLGregorianCalendar endDate);

    /**
     * This XML Web Service method provides information about exchange rates
     * 
     * @param endDate
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExchangeRates", action = "http://www.nbrm.mk/klservice/GetExchangeRates")
    @WebResult(name = "GetExchangeRatesResult", targetNamespace = "http://www.nbrm.mk/klservice/")
    @RequestWrapper(localName = "GetExchangeRates", targetNamespace = "http://www.nbrm.mk/klservice/", className = "mk.nbrm.klservice.GetExchangeRates")
    @ResponseWrapper(localName = "GetExchangeRatesResponse", targetNamespace = "http://www.nbrm.mk/klservice/", className = "mk.nbrm.klservice.GetExchangeRatesResponse")
    public String getExchangeRates(
        @WebParam(name = "StartDate", targetNamespace = "http://www.nbrm.mk/klservice/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.nbrm.mk/klservice/")
        String endDate);

}
